name: Deploy Anime Match
on:
  workflow_run:
    workflows: ["CI Workflow"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop' && github.event.workflow_run.event == 'pull_request' }}
    steps:
      - name: Pull Docker image
        run: docker pull lucaslrodrigues/sprint-api-anilist:latest

      - name: Stop Docker container
        run: docker stop api || true

      - name: Remove Docker container
        run: docker rm api || true

      - name: Run Docker container
        run: docker run --network=bridge --name api -d -p 8081:8081 lucaslrodrigues/sprint-api-anilist:latest
